# Generated by Django 4.2.1 on 2023-05-19 14:22

from django.db import migrations, models
import django_countries.fields
import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_auto_20230518_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="country",
            field=django_countries.fields.CountryField(default="ES", max_length=2),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(default=tasks.models.hoy),
        ),
    ]
